### ISSUE TITLE
Feature request: enhancement: write text layer to image DjVu files, as for PDF

### ISSUE THREAD

**Issue by caganer** [manisandro/gImageReader#371] opened 2018-09-18 22:36 UTC
A substantial increase in functionality imo was introduced a couple of versions back when the option was provided of writing the recognised text to the input PDF as a new hidden searchable text layer. This present request requests that the same functionality be added where the input file is DjVu. 
Currently under MS Windows reliable OCR of DjVu files is available for non-commercial packages it seems only:
1. via DjVuToy invoking MS Office MODI, which does not permit review and correction of recognized text which text is written unchecked into the DjVu file. This method is also reliant on continued free-to-use licensing by MS;
2. via CuneiDjVu whose development has been in stasis for ca.7 years and which fails recognition without diagnosis and does not permit checking;
3. via Djvu.OCR.v2.1 [<genchogencho [AT] abv.bg> as of Nov. 2006] invoking ABBYY FineReader <v.9 frf files; the binary is hard to find and the Windows .hlp file is in old format and Russian language only although the program itself has English/Russian options.

**Comment by manisandro** [comment] 2018-09-19 07:41
One would need to investigate whether the djvulibre API is capable of doing this.

**Comment by manisandro** [comment] 2018-09-27 22:16
Duplicate of #197

**Closed by manisandro** 2018-09-27 22:16 UTC

**Comment by caganer** [comment] 2018-09-28 00:04
Actually I'd like to suggest the revival of the proposal; the thread here 
https://forum.diybookscanner.org/viewtopic.php?f=20&t=3339
has more than 5,000 reads, suggesting the DjVu format at least for scanned books still commands considerable interest, especially given its efficient and smaller file size for b&w text scans - and the open source tools that support same.

**Comment by manisandro** [comment] 2018-09-28 14:28
Sure, I've just closed the issue because it is a duplicate of another already submitted issue (#197), but that other issue is still open.
