### ISSUE TITLE
Feature request: show pages

### ISSUE THREAD

**Issue by prosoitos** [manisandro/gImageReader#329] opened 2018-04-09 04:59 UTC
Thank you so much for a really cool software. I really love it.

There are 2 things that I really miss though. Since they are unrelated, I'll split them in 2 issues.

It would be very convenient to be able to display the pages of a document (for instance, in the left pane): when working with long pdfs, I have to have a pdf reader open to find out the page numbers I need to work on. Having the pages on the left would allow me to spot the right pages directly, from within gImageReader.

Thanks a lot for the amazing work!!! :slightly_smiling_face:

**Comment by manisandro** [comment] 2018-04-09 08:34
Good idea, I'll look into it post 3.3.0.

**Comment by SantosSi** [comment] 2018-04-09 17:39
Sounds like a duplicate of issue #300

**Comment by manisandro** [comment] 2018-04-09 18:33
As I read it is about the source, not the output (i.e. like in most PDF viewers, where on the left you have the thumbnails of the pages of the document, for easier browsing).

**Comment by prosoitos** [comment] 2018-04-09 20:43
Right. Exactly.

Thank you!!!! :slightly_smiling_face:

**Comment by manisandro** [comment] 2020-03-23 00:45
Implemented for Qt in 5eecc5ece26afd14b8e88ced2110b2cb985b6349, Gtk pending.

**Comment by manisandro** [comment] 2020-03-23 20:37
Also done for Gtk.

**Closed by manisandro** 2020-03-23 20:37 UTC
Labels: enhancement

**Comment by prosoitos** [comment] 2020-05-11 04:07
Thank you!! :slightly_smiling_face:
