### ISSUE TITLE
Pofodo do not support much asian fonts

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#262] opened 2017-12-20 11:18 UTC
Hi, I find Pofodo do not support any asian fonts I tested, So Html  maybe a another good format for Tess output. Recently I will implement it.

Haha~~~~

**Comment by manisandro** [comment] 2017-12-20 12:05
The hocr file already html, so what would a html exporter do differently?

**Comment by napasa** [comment] 2017-12-21 00:55
The hocr file  containing relevant position,size information don`t directly restore original layout and present of the pdf OCRED, which is unconvenient to the general user

**Comment by manisandro** [comment] 2017-12-21 12:57
It is pretty difficult to reproduce the layout in HTML, since HTML has no notion of paper size.

**Comment by napasa** [comment] 2017-12-22 10:05
Can we set page size like this **html,body{height:297mm;width:210mm;}**?  I plan to solve asia font problem by converting hOCR file to HTML file, then converting HTML file to PDF file by using QPainter, Here is my demo[hOCR2HTML For gImageReader](https://github.com/napasa/ghOCRToHTML). Now I dont`t know clearly  what the the meaning of every attribute in title property of Element of hOCR file produced by Tess , such as **x_descenders**, **baseline**. Do you know where to find specification for Tess hOCR XML property description?

**Comment by manisandro** [comment] 2017-12-22 10:11
If you plan to feed to to QPainter, it is easier to just use QPainter directly, the code is already there [1]. But QPainter gives you no control over image compression (it always does something like 75% quality jpeg), so the resulting documents can be very large compared to the input. I'd rather invest the energy to look at improving PoDoFo.
What is missing by the way? You should be able to use fonts with asian glyphs in PoDoFo, the "only" problem I'm aware of is that PoDoFo only appears to support RTL text layouts.

[1] https://github.com/manisandro/gImageReader/blob/master/qt/src/hocr/HOCRPdfExporter.cc#L55

**Comment by napasa** [comment] 2017-12-22 10:17
Thanks your advise.  ^_^, I  will try your method to solve it and view your code again

**Comment by napasa** [comment] 2017-12-27 06:52
Hi, Would you mind add a choosing button of pdf export method, like Popper Or Qt Pdf Module. As I tested Qt Pdf Module have great advantage in supporting multi language pdf export. Another question, I don`t find     pdf exporting by qt has distinctive size difference with popper.

**Comment by manisandro** [comment] 2017-12-27 10:39
I suppose you mean PoDoFo, I Poppler isn't used to writing PDFs. I suppose I could add a switch to use the Qt backend, which will only allow for jpeg compressed images.
Size difference: for jpeg it doesn't matter much, but dimensions can be reduced a lot i.e. for black and white or grayscale images if you choose an appropriate compression method.

**Comment by napasa** [comment] 2017-12-28 10:21
Yes, I mean PoDoFo.   I have added a switch to use Qt backend, This is [Export dialog layout](https://drive.google.com/file/d/1sIVHBToKArU1apUZC-j_B_vkdzA6NoWz/view?usp=sharing), Is It OK?

**Comment by napasa** [comment] 2017-12-28 10:27
Another newb question, Every time after I modified code I have to compile total project,  It wastes my lots time and enthusiasm to wait it compile and link success then I could debug it.

**Comment by manisandro** [comment] 2017-12-28 11:13
You can install ccache, then it should be pretty instant. (Actually I never realized that it is recompiling stuff, looks like something is wrong with the cmake setup. I'll take a look. But ccache should already help a ton).

Layout: Should be good, make sure to hide or disable all options which aren't applicable for the Qt backend (essentially compression, password I think). Perhaps you could add a small ? icon next to the combobox with a tooltip explaining the difference (like PoDoFo offering more image format options, whereas Qt having better support for complex scripts).

Thanks!

**Comment by manisandro** [comment] 2017-12-29 13:51
The cmake issue which caused everything to be recompiled all the time should be fixed now btw.

**Comment by manisandro** [comment] 2018-01-04 22:49
Hi, are you still working on this?

**Comment by napasa** [comment] 2018-01-05 06:22
Sorry manisandro, I just had my new years vocations recent seven days,  So I didn`t check any e-mail of remind from github and response to you.  Hi, I am still working on this,  Please leave this proplem to me.

**Comment by manisandro** [comment] 2018-01-05 08:53
No worries - ok

**Comment by manisandro** [comment] 2018-01-29 21:29
Tracking in #291

**Closed by manisandro** 2018-01-29 21:29 UTC
