### ISSUE TITLE
Empty output pane + crash

### ISSUE THREAD

**Issue by raschaa** [manisandro/gImageReader#134] opened 2016-11-12 21:56 UTC
Hi,

I'm having problems with the recent version. Starts up ok, but when I try to recognize the output pane stays empty. If I click recognize again it crashes... tried german and english on same jpeg.

Start from terminal gives this:

```
(gimagereader-gtk:12364): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:12364): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:12364): Gtk-WARNING **: Unknown property: gtkmm__GtkSpinButton.max-width-chars

(gimagereader-gtk:12364): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:12364): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:12364): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:12364): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:12364): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:12364): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:12364): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable
modprobe: ERROR: could not insert 'fglrx': No such device
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: ERROR: could not insert 'fglrx': No such device
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: ERROR: could not insert 'fglrx': No such device
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
[DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 1:AMD Phenom(tm) II X6 1055T Processor score is 0.920317
[DS] Device[2] 1:GeForce GTX 960 score is 0.149880
[DS] Device[3] 0:(null) score is 0.951333
[DS] Selected Device[2]: "GeForce GTX 960" (OpenCL)

(gimagereader-gtk:12364): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:12364): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover
Abgebrochen
```

**Comment by manisandro** [comment] 2016-11-12 22:00
Hi
From the info in the terminal it looks like you are using an OpenCL enabled tesseract build which triggers errors. For a better analysis however I'd need a stack trace. I guess you're using Ubuntu, if so: install `gimagereader-dbg` and then run `gimagereader-gtk` in `gdb`. If you're not experienced with gdb I can give you more precise instructions.

**Comment by raschaa** [comment] 2016-11-13 12:01
Hey,

I have no experience with gdb, but figured I might as well have a look... that's mighty interesting, found I had a problem with my languages but that has not fixed the problem. It didn't crash running in gdb anyways. I see the openCL errors but have no idea what to do with them ;)
If you need more let me know.

thx

```
(gdb) run gimagereader-gtk
Starting program: /usr/bin/gimagereader-gtk gimagereader-gtk
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe8f27700 (LWP 8509)]

(gimagereader-gtk:8508): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:8508): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:8508): Gtk-WARNING **: Unknown property: gtkmm__GtkSpinButton.max-width-chars

(gimagereader-gtk:8508): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:8508): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:8508): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:8508): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:8508): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:8508): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable

(gimagereader-gtk:8508): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `gtkmm__GtkHeaderBar' is not writable
[New Thread 0x7fffe0ae5700 (LWP 8510)]
modprobe: ERROR: could not insert 'fglrx': No such device
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: ERROR: could not insert 'fglrx': No such device
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: ERROR: could not insert 'fglrx': No such device
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
[DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 1:AMD Phenom(tm) II X6 1055T Processor score is 0.920317
[DS] Device[2] 1:GeForce GTX 960 score is 0.149880
[DS] Device[3] 0:(null) score is 0.951333
[DS] Selected Device[2]: "GeForce GTX 960" (OpenCL)
[New Thread 0x7fffd1815700 (LWP 8522)]
[New Thread 0x7fffc8fff700 (LWP 8523)]
[New Thread 0x7fffc3fff700 (LWP 8524)]
[New Thread 0x7fffc37fe700 (LWP 8525)]
[New Thread 0x7fffc2ffd700 (LWP 8526)]
[New Thread 0x7fffc27fc700 (LWP 8527)]
[New Thread 0x7fffc1ffb700 (LWP 8528)]
[New Thread 0x7fffbbfff700 (LWP 8529)]
[New Thread 0x7fffbb7fe700 (LWP 8530)]
[New Thread 0x7fffbaffd700 (LWP 8531)]

(gimagereader-gtk:8508): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

(gimagereader-gtk:8508): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover
[New Thread 0x7fffa6d86700 (LWP 8546)]
[New Thread 0x7fff9ef41700 (LWP 9065)]
[New Thread 0x7fff9e740700 (LWP 9066)]
[New Thread 0x7fff9d4bd700 (LWP 9117)]
OpenCL error code is -44 at   when clCreateKernel kernel_HistogramRectAllChannels .
OpenCL error code is -44 at   when clCreateKernel kernel_HistogramRectAllChannelsReduction .
OpenCL error code is -48 at   when clSetKernelArg imageBuffer .
OpenCL error code is -48 at   when clSetKernelArg numPixels .
OpenCL error code is -48 at   when clSetKernelArg tmpHistogramBuffer .
OpenCL error code is -48 at   when clSetKernelArg imageBuffer .
OpenCL error code is -48 at   when clSetKernelArg tmpHistogramBuffer .
OpenCL error code is -48 at   when clSetKernelArg histogramBuffer .
OpenCL error code is -48 at   when clEnqueueNDRangeKernel kernel_HistogramRectAllChannels .
OpenCL error code is -48 at   when clEnqueueNDRangeKernel kernel_HistogramRectAllChannelsReduction .
OpenCL error code is -44 at   when clCreateKernel kernel_ThresholdRectToPix .
OpenCL error code is -48 at   when clSetKernelArg imageBuffer .
OpenCL error code is -48 at   when clSetKernelArg height .
OpenCL error code is -48 at   when clSetKernelArg width .
OpenCL error code is -48 at   when clSetKernelArg wpl .
OpenCL error code is -48 at   when clSetKernelArg thresholdsBuffer .
OpenCL error code is -48 at   when clSetKernelArg hiValuesBuffer .
OpenCL error code is -48 at   when clSetKernelArg pixThBuffer .
OpenCL error code is -48 at   when clEnqueueNDRangeKernel kernel_ThresholdRectToPix .
OpenCL error code is -44 at   when clCreateKernel kernel_HistogramRectOneChannel .
OpenCL error code is -44 at   when clCreateKernel kernel_HistogramRectOneChannelReduction .
OpenCL error code is -48 at   when clSetKernelArg imageBuffer .
OpenCL error code is -48 at   when clSetKernelArg numPixels .
OpenCL error code is -48 at   when clSetKernelArg tmpHistogramBuffer .
OpenCL error code is -48 at   when clSetKernelArg imageBuffer .
OpenCL error code is -48 at   when clSetKernelArg tmpHistogramBuffer .
OpenCL error code is -48 at   when clSetKernelArg histogramBuffer .
OpenCL error code is -48 at   when clEnqueueNDRangeKernel kernel_HistogramRectAllChannels .
OpenCL error code is -48 at   when clEnqueueNDRangeKernel kernel_HistogramRectAllChannelsReduction .
[Thread 0x7fff9d4bd700 (LWP 9117) exited]
[Thread 0x7fff9ef41700 (LWP 9065) exited]
```

**Comment by manisandro** [comment] 2016-11-13 13:14
So did the program not crash at all repeating the same steps you performed before when it crashed? The fact that you get no output from tesseract is most certaily because of the ton of OpenCL errors. What shouldn't happen is that gImageReader crashes as a result of tesseract failing, it should rather present an error message. So could you try and reproduce the error with gdb active in order to produce a backtrace? As far as the OpenCL errors are concerned, I assume it has something to do with the proprietary fglrx driver, but I'm not experienced with OpenCL so you'll need to pursue this further with the respective upstreams.

**Comment by raschaa** [comment] 2016-11-13 15:01
Nope, no crash... before it would crash when I clicked the recognize button the second time. Now I can click it as much as I like nothing happens, output pane empty....

So, you suggest following up on the fglrx driver? Funny thing is I switched from a ATI GPU to Nvidia GPU about 5 months ago. Seems there is still something leftover that didn't get cleared by the uninstall... hmmm, this could get tricky.

Ty for the heads up

**Comment by manisandro** [comment] 2016-11-13 15:12
Well that is certainly a source of trouble, OpenCL is picking up the fglrx driver, and all the

    ERROR: could not insert 'fglrx': No such device

etc messages indeed point to the fact that no compatible device exists. So yes, it looks like you have a lot of leftovers installed on your system which you'll need to clean up. Taking it to the fglrx maintainers won't help much in this case since it really looks like a configuration issue with your system.

The gtk warnings are related to the gtk version no supporting certain properties, but they should be pretty harmless (it's actually hard to write code which runs without any of the gtk versions out there complaining about some detail :) ).

Don't think there is much I can do gImageReader side here, hence closing.

**Closed by manisandro** 2016-11-13 15:12 UTC

**Comment by raschaa** [comment] 2016-11-13 17:22
Have you seen this?
https://github.com/tesseract-ocr/tesseract/pull/475

**Comment by manisandro** [comment] 2016-11-13 17:24
No - but it still wont fix trying to talk to a nvidia device with a fglrx driver ;)
