### ISSUE TITLE
Change mouse pointer to crosshairs when defining new area

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#312] opened 2018-02-09 23:14 UTC

**Comment by manisandro** [comment] 2018-02-09 23:18
I could only reproduce this in the gtk interface, correct? (Please always specify which interface you refer to)

**Comment by SantosSi** [comment] 2018-02-09 23:22
I could not see it in the Qt5 interface.

**Comment by manisandro** [comment] 2018-02-09 23:23
That is to say that you can't see the crosshair cursor in the qt5 interface?

**Comment by SantosSi** [comment] 2018-02-09 23:24
Yes. Tested with the latest master with Qt5.

**Comment by foghawk** [comment] 2018-03-29 14:09
I believe I have the same issue, but:
- The issue does not occur all the time. Immediately after startup, the crosshairs work as they should. I can't figure out what triggers it, though. It seems to be something related to actually creating an area (as opposed to canceling the selection), but I can start up the application, open the same hOCR file, select the first page, add a graphic region, and it might or might not occur afterwards... sometimes the crosshairs work normally until I interact in some other way with the tree view, sometimes they stop right after that first selection.
- The crosshairs actually _do_ appear—but only for the single pixel between the output pane border and the displayer region. It's moving into the displayer that reverts the cursor back to the arrow.

I've looked at the code and I have no idea why any of this is.

**Comment by manisandro** [comment] 2018-03-29 14:12
I've also observed some odd cursor behaviour in the qt5 interface, and have no idea why. I've seen some odd situations also with other applications, so I'd leaning towards a Qt5 or window manager bug (KWin in my case).

**Comment by foghawk** [comment] 2018-03-29 14:15
I'm on i3; I wouldn't be surprised if it were a Qt thing.

**Comment by manisandro** [comment] 2018-09-28 12:43
Fixed in 1f278be

**Closed by manisandro** 2018-09-28 12:43 UTC
