### ISSUE TITLE
Hocr GTK TreeView issue

### ISSUE THREAD

**Issue by AvtechScientific** [manisandro/gImageReader#559] opened 2022-01-18 12:22 UTC
In the Hocr output (commit 8448a6a407), once I click on certain recognized word within the GTK TreeView - it gets highlighted on the image, but the GTK TreeView jumps to the first top element (instead of remaining at the same clicked word).

**Comment by AvtechScientific** [comment] 2022-01-18 13:13
I don't know whether its related, but I also get this output: `(gimagereader-gtk:6072): Gtk-CRITICAL **: 14:17:31.270: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed`.

**Comment by manisandro** [comment] 2022-01-21 22:02
First issue is fixed in https://github.com/manisandro/gImageReader/commit/caf3e41c1d6f1f1dfaddae3db1b2a2677e96ebd0

I can't reproduce the second issue, do you have an example input?

**Comment by AvtechScientific** [comment] 2022-01-26 16:59
Regarding the second issue - here a [sample imput](https://drive.google.com/file/d/1AlBCTDQDe6kfbQ7RSPazUR480rsY6SWr/view?usp=sharing). Maybe it has something to do with the file being a `.tif`? (As I saved it as `.png` I could not reproduce the issue). On the other side I do remember seeing it also with `.pdf` files...

Here is the [tessdata model](https://gitlab.com/pninim.org/tessdata_heb_rashi/-/raw/main/tesseract_4.1.1/heb_rashi.traineddata) for the provided script.

Thank you very much for all your efforts!

**Comment by manisandro** [comment] 2022-01-28 23:23
I couldn't reproduce the issue, can you try again with 3.4.0 and re-open in case? Thanks

**Closed by manisandro** 2022-01-28 23:23 UTC
