### ISSUE TITLE
Batch export PDF crashes with libqt6 errors

### ISSUE THREAD

**Issue by Draic** [manisandro/gImageReader#609] opened 2023-01-17 14:51 UTC
starting the program and then selecting a folder for batch export will result in a crash if it's set to PDF regardless of the folder or it's contents (can be empty too)

```
gImageReader 3.4.0 ()


#0  0x00007f76d63141b6 in ppoll () from /usr/lib/libc.so.6
#1  0x00007f76d6a7789f in qt_safe_poll(pollfd*, unsigned long, timespec const*) () from /usr/lib/libQt6Core.so.6
#2  0x00007f76d6adb90c in QProcess::waitForFinished(int) () from /usr/lib/libQt6Core.so.6
#3  0x000056432f5d615f in ?? ()
#4  <signal handler called>
#5  0x000056432f60f595 in ?? ()
#6  0x00007f76d6980413 in ?? () from /usr/lib/libQt6Core.so.6
#7  0x00007f76d698637f in QTimer::timeout(QTimer::QPrivateSignal) () from /usr/lib/libQt6Core.so.6
#8  0x00007f76d696bca6 in QObject::event(QEvent*) () from /usr/lib/libQt6Core.so.6
#9  0x00007f76d77759bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#10 0x00007f76d692a258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#11 0x00007f76d6a8499b in QTimerInfoList::activateTimers() () from /usr/lib/libQt6Core.so.6
#12 0x00007f76d6b4f2da in ?? () from /usr/lib/libQt6Core.so.6
#13 0x00007f76d55ae87b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#14 0x00007f76d5605c89 in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x00007f76d55ad132 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#16 0x00007f76d6b4d382 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#17 0x00007f76d6935604 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#18 0x00007f76d79a4b9b in QDialog::exec() () from /usr/lib/libQt6Widgets.so.6
#19 0x000056432f5e4668 in ?? ()
#20 0x00007f76d6980413 in ?? () from /usr/lib/libQt6Core.so.6
#21 0x00007f76d72c8b27 in QAction::triggered(bool) () from /usr/lib/libQt6Gui.so.6
#22 0x00007f76d72cbf89 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt6Gui.so.6
#23 0x00007f76d7874192 in ?? () from /usr/lib/libQt6Widgets.so.6
#24 0x00007f76d78812e5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt6Widgets.so.6
#25 0x00007f76d798130f in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt6Widgets.so.6
#26 0x00007f76d77bd585 in QWidget::event(QEvent*) () from /usr/lib/libQt6Widgets.so.6
#27 0x00007f76d77759bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#28 0x00007f76d776e3a9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#29 0x00007f76d692a258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#30 0x00007f76d776acb9 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt6Widgets.so.6
#31 0x00007f76d77cb7de in ?? () from /usr/lib/libQt6Widgets.so.6
#32 0x00007f76d77ccad5 in ?? () from /usr/lib/libQt6Widgets.so.6
#33 0x00007f76d77759bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#34 0x00007f76d692a258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#35 0x00007f76d6f9a33c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt6Gui.so.6
#36 0x00007f76d6ff7465 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Gui.so.6
#37 0x00007f76d1c143e0 in ?? () from /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#38 0x00007f76d55ae87b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#39 0x00007f76d5605c89 in ?? () from /usr/lib/libglib-2.0.so.0
#40 0x00007f76d55ad132 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#41 0x00007f76d6b4d382 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#42 0x00007f76d6935604 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#43 0x00007f76d692ce7b in QCoreApplication::exec() () from /usr/lib/libQt6Core.so.6
#44 0x000056432f597012 in ?? ()
#45 0x00007f76d623c290 in ?? () from /usr/lib/libc.so.6
#46 0x00007f76d623c34a in __libc_start_main () from /usr/lib/libc.so.6
#47 0x000056432f59bc85 in ?? ()


Thread 13 (Thread 0x7f76bffff6c0 (LWP 19209) "QThread"):
#0  0x00007f76d63140bf in poll () from /usr/lib/libc.so.6
#1  0x00007f76bc3bba6c in ?? () from /usr/lib/libavahi-common.so.3
#2  0x00007f76bc3bb5f1 in avahi_simple_poll_run () from /usr/lib/libavahi-common.so.3
#3  0x00007f76bc3bb7c9 in avahi_simple_poll_iterate () from /usr/lib/libavahi-common.so.3
#4  0x00007f76bc3bb9fe in avahi_simple_poll_loop () from /usr/lib/libavahi-common.so.3
#5  0x00007f76bc3bbacb in ?? () from /usr/lib/libavahi-common.so.3
#6  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#7  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 12 (Thread 0x7f76bcff96c0 (LWP 19207) "Thread (pooled)"):
#0  0x00007f76d629c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007f76d629efd4 in pthread_cond_timedwait () from /usr/lib/libc.so.6
#2  0x00007f76d6a8ba0b in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x00007f76d6a86895 in ?? () from /usr/lib/libQt6Core.so.6
#4  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 11 (Thread 0x7f76bd7fa6c0 (LWP 19206) "Thread (pooled)"):
#0  0x00007f76d629c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007f76d629efd4 in pthread_cond_timedwait () from /usr/lib/libc.so.6
#2  0x00007f76d6a8ba0b in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x00007f76d6a86895 in ?? () from /usr/lib/libQt6Core.so.6
#4  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 10 (Thread 0x7f76bdffb6c0 (LWP 19205) "Thread (pooled)"):
#0  0x00007f76d629c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007f76d629efd4 in pthread_cond_timedwait () from /usr/lib/libc.so.6
#2  0x00007f76d6a8ba0b in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x00007f76d6a86895 in ?? () from /usr/lib/libQt6Core.so.6
#4  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 9 (Thread 0x7f76be7fc6c0 (LWP 19204) "Thread (pooled)"):
#0  0x00007f76d629c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007f76d629efd4 in pthread_cond_timedwait () from /usr/lib/libc.so.6
#2  0x00007f76d6a8ba0b in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x00007f76d6a86895 in ?? () from /usr/lib/libQt6Core.so.6
#4  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 8 (Thread 0x7f76beffd6c0 (LWP 19203) "Thread (pooled)"):
#0  0x00007f76d629c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007
#2  0x00007f76d6a8ba0b in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x00007f76d6a86895 in ?? () from /usr/lib/libQt6Core.so.6
#4  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 7 (Thread 0x7f76bf7fe6c0 (LWP 19198) "Thread (pooled)"):
#0  0x00007f76d629c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007f76d629efd4 in pthread_cond_timedwait () from /usr/lib/libc.so.6
#2  0x00007f76d6a8ba0b in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x00007f76d6a86895 in ?? () from /usr/lib/libQt6Core.so.6
#4  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 6 (Thread 0x7f76c8dff6c0 (LWP 19196) "Thread (pooled)"):
#0  0x00007f76d629c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007f76d629efd4 in pthread_cond_timedwait () from /usr/lib/libc.so.6
#2  0x00007f76d6a8ba0b in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x00007f76d6a86895 in ?? () from /usr/lib/libQt6Core.so.6
#4  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 5 (Thread 0x7f76c9b736c0 (LWP 19195) "libusb_event"):
#0  0x00007f76d63140bf in poll () from /usr/lib/libc.so.6
#1  0x00007f76d60faa95 in ?? () from /usr/lib/libusb-1.0.so.0
#2  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#3  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 4 (Thread 0x7f76ca3746c0 (LWP 19194) "QThread"):
#0  0x00007f76d629c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007f76d629ecd0 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00007f76d6a8ba9c in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /usr/lib/libQt6Core.so.6
#3  0x000056432f650a22 in ?? ()
#4  0x00007f76d6980413 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d6a19eaf in QThread::started(QThread::QPrivateSignal) () from /usr/lib/libQt6Core.so.6
#6  0x00007f76d6a85a08 in ?? () from /usr/lib/libQt6Core.so.6
#7  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#8  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 3 (Thread 0x7f76d0d956c0 (LWP 19193) "QDBusConnection"):
#0  0x00007f76d63140bf in poll () from /usr/lib/libc.so.6
#1  0x00007f76d5605bef in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007f76d55ad132 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007f76d6b4d382 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#4  0x00007f76d6935604 in QEventLoop::exec(QFlags<QEventLoop::ProcessEven
#5  0x00007f76d6a1d778 in QThread::exec() () from /usr/lib/libQt6Core.so.6
#6  0x00007f76d7e1d11f in ?? () from /usr/lib/libQt6DBus.so.6
#7  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#8  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#9  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 2 (Thread 0x7f76d15966c0 (LWP 19192) "QXcbEventQueue"):
#0  0x00007f76d63140bf in poll () from /usr/lib/libc.so.6
#1  0x00007f76d3c3626b in ?? () from /usr/lib/libxcb.so.1
#2  0x00007f76d3c37d1d in xcb_wait_for_event () from /usr/lib/libxcb.so.1
#3  0x00007f76d1c11362 in ?? () from /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#4  0x00007f76d6a85a21 in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007f76d629f8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007f76d6321a60 in ?? () from /usr/lib/libc.so.6


Thread 1 (Thread 0x7f76d3bd4980 (LWP 19191) "gimagereader-qt"):
#0  0x00007f76d63141b6 in ppoll () from /usr/lib/libc.so.6
#1  0x00007f76d6a7789f in qt_safe_poll(pollfd*, unsigned long, timespec const*) () from /usr/lib/libQt6Core.so.6
#2  0x00007f76d6adb90c in QProcess::waitForFinished(int) () from /usr/lib/libQt6Core.so.6
#3  0x000056432f5d615f in ?? ()
#4  <signal handler called>
#5  0x000056432f60f595 in ?? ()
#6  0x00007f76d6980413 in ?? () from /usr/lib/libQt6Core.so.6
#7  0x00007f76d698637f in QTimer::timeout(QTimer::QPrivateSignal) () from /usr/lib/libQt6Core.so.6
#8  0x00007f76d696bca6 in QObject::event(QEvent*) () from /usr/lib/libQt6Core.so.6
#9  0x00007f76d77759bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#10 0x00007f76d692a258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#11 0x00007f76d6a8499b in QTimerInfoList::activateTimers() () from /usr/lib/libQt6Core.so.6
#12 0x00007f76d6b4f2da in ?? () from /usr/lib/libQt6Core.so.6
#13 0x00007f76d55ae87b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#14 0x00007f76d5605c89 in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x00007f76d55ad132 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#16 0x00007f76d6b4d382 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#17 0x00007f76d6935604 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#18 0x00007f76d79a4b9b in QDialog::exec() () from /usr/lib/libQt6Widgets.so.6
#19 0x000056432f5e4668 in ?? ()
#20 0x00007f76d6980413 in ?? () from /usr/lib/libQt6Core.so.6
#21 0x00007f76d72c8b27 in QAction::triggered(bool) () from /usr/lib/libQt6Gui.so.6
#22 0x00007f76d72cbf89 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt6Gui.so.6
#23 0x00007f76d7874192 in ?? () from /usr/lib/libQt6Widgets.so.6
#24 0x00007f76d78812e5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/
#25 0x00007f76d798130f in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt6Widgets.so.6
#26 0x00007f76d77bd585 in QWidget::event(QEvent*) () from /usr/lib/libQt6Widgets.so.6
#27 0x00007f76d77759bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#28 0x00007f76d776e3a9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#29 0x00007f76d692a258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#30 0x00007f76d776acb9 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt6Widgets.so.6
#31 0x00007f76d77cb7de in ?? () from /usr/lib/libQt6Widgets.so.6
#32 0x00007f76d77ccad5 in ?? () from /usr/lib/libQt6Widgets.so.6
#33 0x00007f76d77759bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#34 0x00007f76d692a258 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#35 0x00007f76d6f9a33c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt6Gui.so.6
#36 0x00007f76d6ff7465 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Gui.so.6
#37 0x00007f76d1c143e0 in ?? () from /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#38 0x00007f76d55ae87b in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#39 0x00007f76d5605c89 in ?? () from /usr/lib/libglib-2.0.so.0
#40 0x00007f76d55ad132 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#41 0x00007f76d6b4d382 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#42 0x00007f76d6935604 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#43 0x00007f76d692ce7b in QCoreApplication::exec() () from /usr/lib/libQt6Core.so.6
#44 0x000056432f597012 in ?? ()
#45 0x00007f76d623c290 in ?? () from /usr/lib/libc.so.6
#46 0x00007f76d623c34a in __libc_start_main () from /usr/lib/libc.so.6
#47 0x000056432f59bc85 in ?? ()
```

**Comment by manisandro** [comment] 2023-01-29 15:41
I cannot reproduce this with qt-6.4.2. Can you provide more detailed steps to reproduce?

**Comment by manisandro** [comment] 2023-05-26 22:25
Closing since no feedback, please reopen if still relevant.

**Closed by manisandro** 2023-05-26 22:25 UTC
