### ISSUE TITLE
Handling tables

### ISSUE THREAD

**Issue by KFoster2** [manisandro/gImageReader#452] opened 2020-04-14 12:07 UTC
I´m using gImageReader to run OCR with great results. After that, I need to jump to Word and apply layout fixes to mimic the original. However, it´s not possible to deal with tables when the output generated from gImageReader is a TXT file. Is there any possibility to preserve tables in the final output by using another export method? 

Many thanks in advance!

**Comment by manisandro** [comment] 2020-04-14 12:10
I suppose this is a duplicate of #42 

In short, currently no, tesseract does not return that information currently. But there is some discussion upstream, see [1].

Closing as duplicate of #42.

[1] https://github.com/tesseract-ocr/tesseract/issues/1714

**Closed by manisandro** 2020-04-14 12:10 UTC
