### ISSUE TITLE
Slot Displayer::setCurrentPage gets called twice, when QSpinBox arrow is clicked

### ISSUE THREAD

**Issue by d0b3rm4n** [manisandro/gImageReader#37] opened 2015-10-14 21:01 UTC
While testing the code for issue #30 I noticed that pressing the arrow symbol up or down on the spinBoxPage QSpinBox triggers the slot Displayer::setCurrentPage twice.

It does not happen when arrow-up or arrow-down keys on keyboard are used (when the QSpinBox has the focus). When the number is entered with keyboard also not (unless you enter a 2 digit number, but that could be fixed with:)

    spinBoxPage->setKeyboardTracking(false);

Anyway, here some debug output from my try to find the problem:

    $ QT_MESSAGE_PATTERN="%{time h:mm:ss.zzz} [%{type}] (%{function}:%{line}) - %{message}" ./gimagereader-qt5
    23:49:43.093 [debug] (UI_MainWindow::setupUi:93) - spinBoxPage = new QSpinBox(MainWindow);
    23:49:43.238 [debug] (Displayer::Displayer:76) - connect the signal...
    23:49:43.249 [debug] (ScannerSane::run:68) - sane_init() -> Success
    23:49:43.249 [debug] (ScannerSane::run:74) - SANE version 1.0.24
    23:49:45.051 [debug] (MainWindow::checkVersion:359) - Newest version is: 3.1.2
    23:49:46.566 [debug] (ScannerSane::doRedetect:138) - sane_get_devices() -> Success
    23:50:03.047 [debug] (Displayer::setCurrentPage:101) - setCurrentPage: page 1
    23:50:03.047 [debug] (Displayer::setCurrentPage:103) - who the calls setCurrentPage? QObject(0x0)
    # arrow-up from keyboard used...
    23:50:28.977 [debug] (Displayer::setCurrentPage:101) - setCurrentPage: page 2
    23:50:28.977 [debug] (Displayer::setCurrentPage:103) - who the calls setCurrentPage? QSpinBox(0x9045c30)
    # the 5-key from keyboard used...
    23:51:07.584 [debug] (Displayer::setCurrentPage:101) - setCurrentPage: page 5
    23:51:07.585 [debug] (Displayer::setCurrentPage:103) - who the calls setCurrentPage? QSpinBox(0x9045c30)
    # the arrow up symbol on the QSpinBox pressed (just once...), the slot gets called twice...
    23:51:24.389 [debug] (Displayer::setCurrentPage:101) - setCurrentPage: page 6
    23:51:24.390 [debug] (Displayer::setCurrentPage:103) - who the calls setCurrentPage? QSpinBox(0x9045c30)
    23:51:27.897 [debug] (Displayer::setCurrentPage:101) - setCurrentPage: page 7
    23:51:27.897 [debug] (Displayer::setCurrentPage:103) - who the calls setCurrentPage? QSpinBox(0x9045c30)
    # end program
    23:51:43.809 [debug] (ScannerSane::run:115) - sane_exit()
    23:51:43.882 [debug] (Displayer::setCurrentPage:101) - setCurrentPage: page 1
    23:51:43.883 [debug] (Displayer::setCurrentPage:103) - who the calls setCurrentPage? QSpinBox(0x9045c30)

In order to ensure the Signal-Slot is just connected once, the connection was done with:

    connect(ui.spinBoxPage, SIGNAL(valueChanged(int)), this, SLOT(setCurrentPage(int)), Qt::UniqueConnection);

I also ensured the that singleStep is 1, with:

    spinBoxPage->setSingleStep(1);

The same happens also when compiled against Qt4. It does not happen for any other QSpinBox afaik. Maybe you figure out what the problem is, it's in any case quite annoying.

**Comment by manisandro** [comment] 2015-10-14 21:17
Same seems to happen with the rotation spinbox. The first time it is triggered by the mousedownevent, the second time a misterious event triggers it again.

**Comment by manisandro** [comment] 2015-10-14 21:30
But I actually only see this when setting a breakpoint. If I just ad a

    QTextStream(stdout) << "Page: " << page << endl;

to `Displayer::setCurrentPage` I get the print-out only once. Can you confirm?

**Comment by d0b3rm4n** [comment] 2015-10-29 21:18
Sorry for the late answer. I did my test back then with 2e154aab178 and added a lot of debug output :), so I now checked that out again, with out any changes or additions, but it still steps 2 pages, when clicked on the arrow-down key. Build with:

    cmake -DINTERFACE_TYPE=qt5 ..
    make
    ./gimagereader-qt5

Now also checked out master (f0d7ab69cc0d5), and still I have the same problem (steps 2 pages) (w/o any changes, build as above).

And now just added the following lines on top of master:

     #include <iostream>
    std::cout << "Page: " << page << std::endl << std::flush;

    cmake -DINTERFACE_TYPE=qt5 ..
    make
    $ ./gimagereader-qt5 
    Page: 1
    Page: 2
    Page: 3
    Page: 1
    $

The jump from page 1 to page 3, I clicked the arrow key just once.

I also checked with the version Fedora 22 ships (version 3.1.2), but that version does not have the problem.

**Comment by d0b3rm4n** [comment] 2015-10-29 21:21
BTW I don't observe any issues with the rotation spinbox, it seems just the page spinbox is affected.

**Comment by manisandro** [comment] 2015-11-02 22:08
Hmm, I'm on Fedora rawhide and still cannot reproduce this. If you checkout at tag v3.1.2 and build that version you say you cannot reproduce the issue, right? Could you bisect through the commits to check when the issue appeared? Should be pretty quick since not that many commits have been added since.

One possible cause could be some very low key auto-repeat value (in the sense, if you press the spin box arrow without releasing the button, after a short delay the auto-repeat will kick in). This however would not explain why it only appears to happen with version after v3.1.2. (I do not set any auto-repeat timeout in the gImageReader code).

**Comment by d0b3rm4n** [comment] 2015-11-27 12:40
So I finally found the time to search for the commit which makes problems: f5aeccd

Up to a7d5daf it still works fine, from f5aeccd onwards (where you seem to have made changes wrt to that) it starts having the problem for me.

WRT to "very low key auto-repeat value" I try to just shortly press the mouse button :) and would be very surprised if I so far managed to always just trigger it in that very specific spinbox, but not in others, e.g. the rotation spinbox.

And I'm still on an to date Fedora release 22.

**Comment by d0b3rm4n** [comment] 2015-11-27 12:44
Ah and I didn't change any of the code, I used just your plain commits.

**Comment by manisandro** [comment] 2015-11-27 15:33
Okay, so it is definitely something with the code. I'll try to figure out what might be wrong. Thanks for bisecting!

**Comment by d0b3rm4n** [comment] 2015-11-29 11:28
I freshly installed Fedora 23 at the same I changed from i586 to x86_64 architecture on my system. So far I can still reproduce the issue on f5aeccd and higher, while on a7d5daf it works fine.

**Comment by Hallot** [comment] 2015-12-11 13:29
This is probably a timer issue, which is why it might not appear for everyone.
Basically, if the slot connected to the SpinBox takes a long time, the mouse button released event takes some time to happen, and the timer that check if the mouse is kept pressed (to keep on increasing/decreasing the SpinBox) fires before it arrives. The SpinBox thinks the user want to keep on clicking on the SpinBox, and thus the slot is called twice.
See this for more information: http://www.qtcentre.org/archive/index.php/t-43078.html

**Comment by manisandro** [comment] 2016-01-13 22:50
Thanks @d0b3rm4n and @Hallot for the helpful tip , this was indeed the issue. Fixed by disabling the spinbox while the page is being set. Fixed in daf6280.

**Closed by manisandro** 2016-01-13 22:50 UTC
