### ISSUE TITLE
No stripping of line breaks

### ISSUE THREAD

**Issue by Freredaran** [manisandro/gImageReader#498] opened 2021-02-24 13:15 UTC
I use gImage 3.3.1 (on Ubuntu 20.04) several times a day for converting pdf patents into text for translation purposes.
There seems to be no way to avoid line breaks with the configuration options under "Keep line break if..." in the output pane toolbar.
One interesting option would be to be able to search for line breaks and other format marks with the Find/Replace tool.
Thank you much for your excellent software :o)

![gImage](https://user-images.githubusercontent.com/79581136/109039619-47359800-76cd-11eb-9004-988b99b13f11.png)

**Comment by chopinesque** [comment] 2021-08-10 05:44
Maybe this site could help fix that: https://www.pastemagic.com/ (choose "remove line breaks")

**Comment by manisandro** [comment] 2022-01-12 23:51
I guess this is a duplicate of #373

**Closed by manisandro** 2022-01-12 23:51 UTC
