### ISSUE TITLE
jp2 file OCR is failing

### ISSUE THREAD

**Issue by Shreeshrii** [manisandro/gImageReader#194] opened 2017-10-11 05:46 UTC
jp2 files are being displayed ok, but the OCR is failing with a program crash.

![jp2-crash](https://user-images.githubusercontent.com/5095331/31424018-9ebc9a98-ae75-11e7-9a90-78ade5432de6.png)

**Comment by manisandro** [comment] 2017-10-11 07:42
Can you share this image? I doubt that it is related to the file format, since they are all raw RGBA buffers by the time they are passed to the OCR engine, but possibly tesseract is stumbling on its content (especially if you are using the 4.0.0. alpha build).

**Comment by Shreeshrii** [comment] 2017-10-11 08:40
Yes, it is 4.0.0alpha build.

 I was able to OCR pages from same book as pdf, also pages extracted from
book as png.

I will upload the jp2 file for you to test.

**Comment by manisandro** [comment] 2017-10-11 08:43
It's probably related to some compression related pixel pattern (since jp2 is a compressed format, whereas png is lossless).

**Comment by manisandro** [comment] 2017-10-11 21:30
Actually this appears to be some windows specific crasher in the openjpeg decoder. I can get gImageReader to crash by simply zooming around a bit with the images you provided...

**Comment by manisandro** [comment] 2017-10-11 22:01
Hm, no idea what's going on here. I can only reproduce it on Windows, and neither the debugger nor the memory analyzer really give me any clue.

**Comment by Shreeshrii** [comment] 2017-10-12 03:32
I will check whether I am able to open in irfan view on Windows 10.

**Comment by Shreeshrii** [comment] 2017-10-12 03:35
http://www.openjpeg.org/2017/10/04/OpenJPEG-2.3.0-released

New release a few days back. You could try using it.

**Comment by manisandro** [comment] 2017-10-12 07:38
Already using openjpeg2-2.3.0

**Comment by Shreeshrii** [comment] 2017-10-14 08:47
Able to open these jp2 files ok in irfanview on windows 10.

**Comment by ZaMaZaN4iK** [comment] 2017-10-15 21:57
@manisandro did you find reason of the issue?

**Comment by manisandro** [comment] 2017-10-16 08:13
@ZaMaZaN4iK No luck so far...

**Comment by ZaMaZaN4iK** [comment] 2018-01-30 23:14
@manisandro what is the status of the issue?

**Comment by manisandro** [comment] 2018-01-30 23:15
Reproducible but no clue what's going on, feel free to have a look ;)

**Comment by WRFan** [comment] 2020-01-16 04:53
The crash is caused by the code inside the function "Displayer::scaleThread" in displayer.cc:

	if (req.type == ScaleRequest::Scale)
	{
		m_scaleMutex.unlock(); // crashes

[QMutex](https://doc.qt.io/qt-5/qmutex.html#unlock)

> Unlocking a mutex that is not locked results in undefined behavior

Might be the reason. Although, why aren't jpeg etc. images choking here???

Running a jp2 image thru this function is a bad idea in general; let's bypass the crash and see what happens afterwards:

	bool IsJp2 = m_currentSource->displayname.endsWith(".jp2", Qt::CaseInsensitive);

	if (!IsJp2) m_scaleMutex.unlock();

	QImage image = m_renderer->render(req.page, req.scale * req.resolution);

	double i2 = image.isNull(); char myString[50]; sprintf(myString, "%lf", i2); // true

true what?! why is it a null image? That's why: the "render" func above points to QImage ImageRenderer::render func in displayrenderer.cc:

	QImage ImageRenderer::render(int page, double resolution) const // my1
	{
		QImageReader reader(m_filename);

		...

		QSize nSize = reader.size() * resolution / 100.0;

		reader.setScaledSize(nSize);

		double i2 = reader.size().isValid(); char myString[50]; sprintf(myString, "%lf", i2); // false

false?! what the...?!

Let's assume an image 1917x2856. Using jpeg format:

	double i2 = reader.size().width(); char myString[50]; sprintf(myString, "%lf", i2); // 1917

	double i2 = reader.size().height(); char myString[50]; sprintf(myString, "%lf", i2); // 2856

Now same image converted to jp2:

	double i2 = reader.size().width(); char myString[50]; sprintf(myString, "%lf", i2); // -1

	double i2 = reader.size().height(); char myString[50]; sprintf(myString, "%lf", i2); // -1

[QSize::isValid](https://doc.qt.io/qt-5/qsize.html#isValid)

	Returns true if both the width and height is equal to or greater than 0

setScaledSize works, but only if nSize isn't off to much, otherwise we end up with a null image. In any case, the image returned is unscaled, it's always either a null image or a an unscaled image

	reader.setScaledSize(reader.size()); // ok, but unscaled

	reader.setScaledSize(reader.size() * 0.51); // ok, but unscaled

	reader.setScaledSize(reader.size() * 0.5); // null image for anything below 0.51

Let's see what happens now if a valid image is returned:

	if (image.isNull()) continue;

	m_scaleMutex.lock(); // HANGS

Hangs. Can't close the programme any longer the standard way, had to crash it to get it out of memory. QT can't obtain the lock on this file for some reason, it seems, it just sits there and waits for the lock to be released, except it's not locked, so QT will sit there forever waiting.

Even if you get the jp2 thru the function, what good is it? The user clicks the zoom button, image is zoomed, what happens now?

	if (m_scale < 1.)
	{
		m_pendingScaleRequest = ...
	}

We end up inside the "ImageRenderer::render" function again, it scales the image back to reader.size(), i.e. to original size, which is extremely nice to see - I zoom in or out, the programme zooms back to scale 1.

The fact however that the zoom buttons are working shows the image IS scalable, just not thru QImageReader.

Personally, I don't see a point in having this function AT ALL. What is it for? To react to the user's resizing of the app window? Why react? This resize event is annoying both in the browser on the internet as well as in programmes. Don't. If a user wants to zoom, there's the zoom buttons right in front of him, we can do it ourselves. So I disabled the entire func, and good riddance, I say.

On the whole, I gotta say this jp2 format is the most annoying thingy I've ever witnessed. My woes began back on WinXP when this drek format appeared, I scouted the internet for ages to get support.

Recently, I cleaned up the registry, fixed some entries for the image properties menu of windows explorer, tried to add the properties to jp2, nada. Windows Explorer doesn't support this format, it doesn't know what it is, it doesn't care. All MS system components fail to work, now just explorer, photoviewer.dll as well, which I use to display images.

Have you tried to open an jp2 image in Acrobat? It will open it,  but the result looks like shit and scaling the page doesn't work properly. I can open jp2 images in Corel Photopaint all right, in fact I had too, since this format is so widely used, I haven't seen a single jp2 image on the entire WWW. Had to convert an image myself for testing purposes.

Now a couple of words about compilation. First, it is incredibly pleasant to download 2.5 GB of source files and unpack 25.000 files to extract 200 KB of data. Second, the QT asses try to impose their qmake.exe drek on us for compilation purposes, thanx, but I desist, now matter how they insist. So I wrote a cmakelists.txt, compiled it without probs using CMAKE_AUTOMOC without much ado, which surprised me, really, but QT failed to recognize the plugin as a supported format. I was going mad, performing ritual dances around the computer, that didn't help. So I used their damn qmake.exe, it was whining about missing files here, missing files there, missing files everywhere, but I finally got it to compile an nmake Makefile.Release. Looking inside I witness:

`
DEFINES = -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DNDEBUG -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -D_WINDLL
`

I am adding everything to target_compile_definitions, BAM! plugin is working. I finally narrowed it down to "QT_NO_DEBUG"

	target_compile_definitions(qjp2 PUBLIC QT_NO_FOREACH QT_NO_JAVA_STYLE_ITERATORS QT_NO_DEBUG)

> Q_ASSERT(), Q_ASSERT_X(), and Q_CHECK_PTR() expand to nothing if QT_NO_DEBUG is defined during compilation.

No idea. Looks like erroneous source code. Ask THEM, QT gotta know, they wrote the crappy plugin.

**Comment by manisandro** [comment] 2020-01-16 23:49
Thanks for your investigation! I seem to recall that this happens on Windows only, but I'll need to try again whether I can reproduce it under Linux as well.

> Personally, I don't see a point in having this function AT ALL.

What function are you refering to here?

**Comment by WRFan** [comment] 2020-01-22 01:53
>What function are you refering to here?

well, I mean the function that is causing the crash,

	void Displayer::scaleThread()

inside displayer.cc

>jp2 files are being displayed ok, but the OCR is failing with a program crash.

the initial poster seems to get the crash on OCR-ing, while I was getting the crash when opening jp2 files. However, I had another problem with tesseract, it's tesseract related, but obviously causes problems with gImageReader as well - it's crashing on my system when avx2 is used with error 0xc000001d, which seems to suggest tesseract is calling some function that is not supported on windows. This problem is known to tesseract developers, someone already reported it to them back in good old WinXP days, they are just too lazy to deal with it. The problem is probably unrelated to the original poster, since he says he can OCR png images, while on my system ANY OCR attempt leads to a crash if avx2 is used. The problem is probably inside intsimdmatrixavx2.cpp. For a stand-alone tesseract it's possible to disable avx2 by passing

	-c dotproduct=avx

on the command-line, but I can't pass this thru gImageReader, so gImageReader was crashing too, until I disabled avx2 in simddetect.cpp, then recompiled everything. After disabling it I have no problems OCR-ing images, including jp2 images.

**Comment by manisandro** [comment] 2020-03-21 14:05
This appears to be fixed in latest master, either by a548c6f501b855c6357baacec83707f02c1c6e63 or by 1d025e55a489b961e8a6f40f08827004201d39ca

**Closed by manisandro** 2020-03-21 14:05 UTC
